cluster: "~/.config/snakemake/pbs-torque/pbs-submit.py " # N.B. this is commented out because the cluster scheduler seems to purge information about completed jobs very quickly, creating issues with "Unknown Job Ids" --depend \"{dependencies}\""
cluster-status: "~/.config/snakemake/pbs-torque/pbs-status.py"
jobscript: "~/.config/snakemake/pbs-torque/pbs-jobscript.sh"
jobs: 500
immediate-submit: False
verbose: true
